### ISSUE TITLE
Issue after update to Version 1.0.12

### ISSUE THREAD

**Issue by harrypotter06** [JoomTools/plg_system_jtaldef#4] opened 2022-07-30 22:47 UTC
Hello,

im am install (update) your last package on Joomla 3.10.X
Now if i go to the plugin, i got an error: _Class 'JFormFieldList' not found_

Please can you fix it an update the install package?

Please can you implement the fonts from: https://use.fontawesome.com/

Thanks for your support and best regards
Klaus

**Comment by degobbis** [comment] 2022-07-31 07:27
Hi Klaus,

sorry, but I can't reproduce this error.
Please give me more details:
- PHP version
- Is the Issue on backend or frontend
- List of non core extensions that are installed
- A step by step instruction to reproduce this 
- Enable the system debug in global configuration and set error reporting to develop or maximum and return the error

Because of fontawesome, the implementation is planned, I just lack the time.

**Comment by harrypotter06** [comment] 2022-07-31 11:14
Hi,

the issue is in Backend.
Only Exist on version 1.0.12 and not on 1.0.3

We use Joomla 3.10.X and PHP 7.4.10.

To reproduce:

1. Install Version 1.0.12
2. go to “Plugin”
3. Select Plugin to config and got this error

What „List of non core extensions” did you mean? All System-Plugins

Here the Debug-Output:

***@***.***

Thanks & Best Regards
Klaus


Von: Guido De Gobbis ***@***.***>
Gesendet: Sonntag, 31. Juli 2022 09:27
An: joomtools/plg_system_jtaldef ***@***.***>
Cc: Klaus Krönert ***@***.***>; Author ***@***.***>
Betreff: Re: [joomtools/plg_system_jtaldef] Issue after update to Version 1.0.12 (Issue #4)


Hi Klaus,

sorry, but I can't reproduce this error.
Please give me more details:

  *   PHP version
  *   Is the Issue on backend or frontend
  *   List of non core extensions that are installed
  *   A step by step instruction to reproduce this
  *   Enable the system debug in global configuration and set error reporting to develop or maximum and return the error

Because of fontawesome, the implementation is planned, I just lack the time.

**Comment by degobbis** [comment] 2022-07-31 16:27
Hi,

I'm still not getting the error you reported.

The debug output is not shown in your reply, so I can't understand how and where the error is produced.

Non-core extensions are all extensions that were installed later (not supplied with Joomla).

**Comment by degobbis** [comment] 2022-08-23 14:39
Hi Klaus,

I'll wait for the debug output if the error still persists, otherwise please close the issue with a short comment.

**Comment by kruemelmonster2001** [comment] 2022-08-23 17:47
I think I have the same error, when opening the Plugin to set the config I get this error:

`<html><body>
<blockquote>
						<span class="label label-inverse">0</span> Class 'JFormFieldList' not found													<br>/home/www/scheiber/plugins/system/jtaldef/field/jtaldefhandlertoparse.php:24											</blockquote>
											<div>
							

Call stack
--
# | Function | Location
1 | () | JROOT/plugins/system/jtaldef/field/jtaldefhandlertoparse.php:24
2 | require_once() | JROOT/libraries/src/Form/FormHelper.php:243
3 | Joomla\CMS\Form\FormHelper::loadClass() | JROOT/libraries/src/Form/FormHelper.php:120
4 | Joomla\CMS\Form\FormHelper::loadType() | JROOT/libraries/src/Form/FormHelper.php:76
5 | Joomla\CMS\Form\FormHelper::loadFieldType() | JROOT/libraries/src/Form/Form.php:1985
6 | Joomla\CMS\Form\Form->loadFieldType() | JROOT/libraries/src/Form/Form.php:1922
7 | Joomla\CMS\Form\Form->loadField() | JROOT/libraries/src/Form/Form.php:359
8 | Joomla\CMS\Form\Form->getFieldset() | JROOT/layouts/joomla/edit/fieldset.php:16
9 | include() | JROOT/libraries/src/Layout/FileLayout.php:125
10 | Joomla\CMS\Layout\FileLayout->render() | JROOT/libraries/src/Layout/LayoutHelper.php:73
11 | Joomla\CMS\Layout\LayoutHelper::render() | JROOT/administrator/components/com_plugins/views/plugin/tmpl/edit.php:106
12 | include() | JROOT/libraries/src/MVC/View/HtmlView.php:701
13 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/libraries/src/MVC/View/HtmlView.php:230
14 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT/administrator/components/com_plugins/views/plugin/view.html.php:45
15 | PluginsViewPlugin->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:664
16 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/administrator/components/com_plugins/controller.php:51
17 | PluginsController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:702
18 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/administrator/components/com_plugins/plugins.php:19
19 | require_once() | JROOT/libraries/src/Component/ComponentHelper.php:402
20 | Joomla\CMS\Component\ComponentHelper::executeComponent() | JROOT/libraries/src/Component/ComponentHelper.php:377
21 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:101
22 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:159
23 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:225
24 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/index.php:51

</div>
</body>
</html>`

**Comment by degobbis** [comment] 2022-08-23 19:37
@kruemelmonster2001 @harrypotter06 please test this version:

[plg_system_jtaldef-1.0.13-dev.zip](https://github.com/joomtools/plg_system_jtaldef/files/9410156/plg_system_jtaldef-1.0.13-dev.zip)

**Comment by kruemelmonster2001** [comment] 2022-08-24 04:12
Hi, this Version can be configured in Backend!

Great job!

But I am Getting 404 after activating the PlugIn.

I am using an Joomlashine Template an Configured the in After <head> section
<link href="https://fonts.googleapis.com/css2?family=PT+Sans+Caption:wght@400;700&family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet" />

and in an user CSS the:
    @import "https://fonts.googleapis.com/css2?family=PT+Sans+Caption:wght@400;700&family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap";
    @import url("https://fonts.googleapis.com/css2?family=PT+Sans+Caption:wght@400;700&family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap");
    @import url(https://fonts.googleapis.com/css2?family=PT+Sans+Caption:wght@400;700&family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap);


Or did I understood the configuration wrong?

Is It possible to send you a private message?

Greetings

Jürgen

**Comment by harrypotter06** [comment] 2022-08-24 09:17
Hi,

yes it will be configured in Backend! 
404 i don't have


Thanks
Klaus

**Comment by degobbis** [comment] 2022-08-24 09:44
@kruemelmonster2001 You can contact me directly on Ringcentral (Glip) as Guido De Gobbis or on Discord as deGobbis.

**Comment by degobbis** [comment] 2022-08-24 09:53
@kruemelmonster2001 As a part of the german community you can follow this instructions:
https://www.joomla.de/community/glip

**Comment by degobbis** [comment] 2022-08-25 07:27
Error `JFormFieldList` not found on line 24 in `/home/www/scheiber/plugins/system/jtaldef/field/jtaldefhandlertoparse.php` fixed with version [1.0.13](https://github.com/joomtools/plg_system_jtaldef/releases/tag/1.0.13).

**Closed as completed by degobbis** 2022-08-25 07:27 UTC
